version: "2"
services:
  mydb:
    build: ./mysql
    container_name: "mysql5.7"
    restart: always
    ports:
      - "43306:3306"
    volumes:
      - E:/project/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  myredis:
    build: ./redis
    container_name: "redis3.2"
    restart: always
    ports:
      - "46379:6379"
    volumes:
      - E:/project/redis:/data
  myphp:
    build: ./php
    container_name: "php7.2"
    restart: always
    ports:
      - "49000:9000"
    volumes:
      - E:/project/www:/var/www/html
      - E:/project/php:/usr/local/etc/php
    links:
      - "mydb"
      - "myredis"
  mynginx:
    build: ./nginx
    container_name: "nginx"
    restart: always
    ports:
      - "40000:80"
      - "40080:8000"
      - "40081:8001"
      - "40082:8002"
      - "40083:8003"
      - "40084:8004"
      - "40085:8005"
    links:
      - "myphp"
      - "mydb"
    volumes:
      - E:/project/www:/usr/share/nginx/html
      - E:/project/nginx:/etc/nginx
      - E:/project/logs/nginx.logs:/var/log/nginx
